--- # Ansible playbook for preparing Ubuntu 16.04 VM for packstack-openstack installation
- hosts: hetzner_singlenode_testing
  gather_facts: no
  tasks: 
  - name: Setup required repositories - cloud-archive:stein
    apt_repository: 
      repo: cloud-archive:stein
      state: present
  - name: Update all packages and repo information
    apt:
      name: '*'
      state: latest
      update_cache: yes
  - name: Install Packstack installer
    apt: 
      name: openstack-packstack
      state: latest
  - name: Install additional packages
    apt:
      pkg:
      - vim
      - chrony





## needs ansible 2.7.0 for this to work
#  - name: Reboot the machine to apply packages
#    reboot:
#      reboot_timeout: 600
#      test_command: uptime
       
